# typed: strict
# frozen_string_literal: true

# Code generated by protoc-gen-rbi. DO NOT EDIT.




class SimplePb::EmptyValidators
  extend T::Sig
  include Validation
  include SimplePb


  include T::Props::Serializable
  include T::Struct::ActsAsComparable


  sig {
      returns(T::Array[MessageValidator[SimplePb::Empty]])
  }
  def all_model_validators
    [

    ]
  end
end



class SimplePb::SimpleValidators
  extend T::Sig
  include Validation
  include SimplePb


  include T::Props::Serializable
  include T::Struct::ActsAsComparable

  sig {
    returns ValidatableField[SimplePb::Simple, T.nilable(String)]
  }
  def int32_field
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.int32_field },
      setter: ->(message, field) { message.int32_field = field },
      validators: [
        
      ]
    )
  end


  sig {
      returns(T::Array[MessageValidator[SimplePb::Simple]])
  }
  def all_model_validators
    [
        int32_field.message_validator,

    ]
  end
end



class SimplePb::FooValidators
  extend T::Sig
  include Validation
  include SimplePb


  include T::Props::Serializable
  include T::Struct::ActsAsComparable

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def s
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.s },
      setter: ->(message, field) { message.s = field },
      validators: [
        Validation::ValidateSubMessage.new(SimpleValidators.new.all_model_validators),
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def ss
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.ss },
      setter: ->(message, field) { message.ss = field },
      validators: [
        Validation::ValidateSubMessageList.new(SimpleValidators.new.all_model_validators),
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def optional_s
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.optional_s },
      setter: ->(message, field) { message.optional_s = field },
      validators: [
        Validation::Required.new,
        Validation::ValidateSubMessageIfPresent.new(SimpleValidators.new.all_model_validators),
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def colour
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.colour },
      setter: ->(message, field) { message.colour = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def colours
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.colours },
      setter: ->(message, field) { message.colours = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def optional_colour
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.optional_colour },
      setter: ->(message, field) { message.optional_colour = field },
      validators: [
        Validation::Required.new,
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def int_field
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.int_field },
      setter: ->(message, field) { message.int_field = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def int_fields
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.int_fields },
      setter: ->(message, field) { message.int_fields = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def optional_int_field
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.optional_int_field },
      setter: ->(message, field) { message.optional_int_field = field },
      validators: [
        Validation::Required.new,
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def int64_field
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.int64_field },
      setter: ->(message, field) { message.int64_field = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def int64_fields
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.int64_fields },
      setter: ->(message, field) { message.int64_fields = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def optional_int64_field
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.optional_int64_field },
      setter: ->(message, field) { message.optional_int64_field = field },
      validators: [
        Validation::Required.new,
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def timestamp_field
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.timestamp_field },
      setter: ->(message, field) { message.timestamp_field = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def timestamp_fields
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.timestamp_fields },
      setter: ->(message, field) { message.timestamp_fields = field },
      validators: [
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def optional_timestamp_field
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.optional_timestamp_field },
      setter: ->(message, field) { message.optional_timestamp_field = field },
      validators: [
        Validation::Required.new,
        
      ]
    )
  end

  sig {
    returns ValidatableField[SimplePb::Foo, T.nilable(String)]
  }
  def oo
    ValidatableField.new(
      translation: "<nil>",
      getter: ->(message) { message.oo },
      setter: ->(message, field) { message.oo = field },
      validators: [
        ]
    )
  end


  sig {
      returns(T::Array[MessageValidator[SimplePb::Foo]])
  }
  def all_model_validators
    [
        s.message_validator,
        ss.message_validator,
        optional_s.message_validator,
        colour.message_validator,
        colours.message_validator,
        optional_colour.message_validator,
        int_field.message_validator,
        int_fields.message_validator,
        optional_int_field.message_validator,
        int64_field.message_validator,
        int64_fields.message_validator,
        optional_int64_field.message_validator,
        timestamp_field.message_validator,
        timestamp_fields.message_validator,
        optional_timestamp_field.message_validator,

        oo.message_validator,
    ]
  end
end

