# typed: strict
# frozen_string_literal: true

# Code generated by protoc-gen-rbi. DO NOT EDIT.

module SimplePbService
  extend T::Sig

  sig do
    params(mapper: ActionDispatch::Routing::Mapper).void
  end
  def self.add_routes(mapper)

  end


end
